---
title: "Project Euler - 99"
output: html_notebook
---

Largest exponential

Comparing two numbers written in index form like 211 and 37 is not difficult, as any calculator would confirm that 211 = 2048 < 37 = 2187.

However, confirming that 632382^518061 > 519432^525806 would be much more difficult, as both numbers contain over three million digits.

Using base_exp.txt (right click and 'Save Link/Target As...'), a 22K text file containing one thousand lines with a base/exponent pair on each line, determine which line number has the greatest numerical value.

NOTE: The first two lines in the file represent the numbers in the example given above.

That should be simple. I think. 

log(a) > log(b), if a > b.

Also: log(a^x) = x*log(a)

The hypothesis is, that if I calculate exponent*log(base) for all lines in the file, I will be able to determine
which line has the largest exponent*log(base) value. That will also be the line where base^exponent is the 
largest.

There is a small caveat: Nasty people might want to chose pairs where the values of exponent*log(base) are very
close, as in too close to determine the difference, given the precision R has.



log(a^x) = x*log(a)

518061*log(632382) > 525806*log(519432)

632382*log(518061)
filnavn <- "p099_base_exp.txt"
df <- readLines(filnavn)
View(df)

library(dplyr)
library(stringr)
library(magrittr)
library(tibble)
library(tidyr)
answer <- df %>% 
  enframe() %>% 
  separate(value, c("first", "second") ) %>% 
  mutate(res=as.numeric(second)*log(as.numeric(first))) %>% 
  arrange(desc(res)) %>% 
  slice(1) %>% 
  select(name) %>% 
  as.numeric()

answer

mutate(base )


## evt noget ældre

Comparing two numbers written in index form like 211 and 37 is not difficult, as any calculator would confirm that 211 = 2048 < 37 = 2187.

However, confirming that 632382^518061 > 519432^525806 would be much more difficult, as both numbers contain over three million digits.

Using base_exp.txt (right click and 'Save Link/Target As...'), a 22K text file containing one thousand lines with a base/exponent pair on each line, determine which line number has the greatest numerical value.

NOTE: The first two lines in the file represent the numbers in the example given above.

log(a^x) = x*log(a)

518061*log(632382) > 525806*log(519432)

632382*log(518061)
filnavn <- "p099_base_exp.txt"
df <- readLines(filnavn)
View(df)

library(dplyr)
library(stringr)
library(magrittr)
library(tibble)
library(tidyr)
answer <- df %>% 
  enframe() %>% 
  separate(value, c("first", "second") ) %>% 
  mutate(res=as.numeric(second)*log(as.numeric(first))) %>% 
  arrange(desc(res)) %>% 
  slice(1) %>% 
  select(name) %>% 
  as.numeric()

answer

mutate(base )