---
title: "Euler 61"
output: html_document
date: '2018-04-19'
params:
  done: T
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Four-digit triangle-numbers:

```{r}
P3 <- function(x){
  x*(x+1)/2
}
L3 <- P3(45:140)
```


Square numbers:
```{r}
P4 <- function(x){
  x*x
}
L4 <- P4(32:99)

```


Pentagonal:
```{r}
P5 <- function(x){
  x*(3*x -1)/2
}
L5 <- P5(26:81)

```


Hexagonal
```{r}
P6 <- function(x){
  x*(2*x-1)
}
L6 <- P6(23:70)

```


Heptagonal:
```{r}
P7 <- function(x){
  x*(5*x-3)/2
}
L7 <- P7(21:63)

```


Octagonal:
```{r}
P8 <- function(x){
  x*(3*x-2)
}
L8 <- P8(19:58)

```


Lets get them all into a list:
```{r}
values <- list(L8, L7, L6, L5, L4, L3)
```



A lot of nested for-loops. There has to be a better way:
```{r}
for(i in values[[1]]){
  for(b in 2:6){
    if(length(values[[b]][(values[[b]] %/% 100) == (i %% 100)])==0){
        next()
      }
    for(j in values[[b]][(values[[b]] %/% 100) == (i %% 100)]){
      for(c in setdiff(2:6, b)){
       if(length( values[[c]][(values[[c]] %/% 100) == (j %% 100)]  )==0){
         next()
       }
       for(k in values[[c]][(values[[c]] %/% 100) == (j %% 100)]){
         for(d in setdiff(2:6, c(b,c))){
           if(length( values[[d]][(values[[d]] %/% 100) == (k %% 100)]  )==0){
         next()
       }
           for(l in values[[d]][(values[[d]] %/% 100) == (k %% 100)]){
             for(e in setdiff(2:6, c(b,c,d))){
               if(length( values[[e]][(values[[e]] %/% 100) == (l %% 100)]  )==0){
         next()
       }
               for(m in values[[e]][(values[[e]] %/% 100) == (l %%100)]){
                  for(f in setdiff(2:6, c(b,c,d,e))){
                    if(length( values[[f]][(values[[f]] %/% 100) == (m %% 100)]  )==0){
                    next()
                     } else{
                    for(n in values[[f]][(values[[f]] %/% 100) == (m %% 100)]){
                          if((n %% 100) == (i %/% 100)){
                        answer <- sum(i,j,k,l,m,n)
                        break()
                      }}
                    }
                  }   
               }
             } 

           }
          }
       }
     }
    }
  }
}

```

