---
title: "Euler 327"
output: html_document
date: '2023-05-27'
params:
  done: F
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


C er det maksimale antal kort. 

For R lig 3 og C = 3, kan vi komme gennem de sidste to rum (C-1) uden at skulle 
vende tilbage.

Når vi er på vej tilbage og er ved start, skal vi have 0 kort. Så får vi udleveret
flere.

3 kort, gennem første dør 1 i kassen retur
3 kort - gennem første dør 1 i kassen retur
3 kort, gennem første dør 

øvelsen er at få placeret C kort i rum C-1

R-C-1 der skal vi have C kort. 

ved R = 3, skal vi have 3 kort når vi er nået til rum 1. 
Ved R = 4, skal vi have 3 kort når vi når rum 2
Ved R = 5, skal vi have 3 kort når vi når rum 3
ved R = 6 skal vi have 3 kort når vi når rum 4.

Eller - ved R rum skal vi have C kort når vi når rum R-C-1

For at komme til rum 1 og tilbage skalvi bruge 2 kort.

for at komme til rum 2 og tilbage, skal vi bruge 4 kort.

for at komme til rum 3 og tilbage, skal vi bruge 6 kort.

Så for at komme til et givet rum r, skal vi bruge 2*r kort. Og hvis det er større
end C skal de deponeres undervejs.


