---
title: "Euler 44"
output: html_document
date: '2023-05-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Project Euler 44 - Pentagon numbers

A pentagonal number is generated by the formula:

P~n~ = n(3n-1)/2

I must now find the pair of pentagonal numbers P~j~ and P~k~ where the sum P~j~ + P~k~ is also pentagonal.

And where P~j~ - P~k~ is pentagonal.

And where D = |P~j~ - P~k~| is minimised.

The answer is D.

First I'll make a function generating pentagonal numbers:

pent <- function(x){
  x*(3*x - 1)/2
}


Nice and vectorized.

I can check it by calculating the first ten pentagonal numbers:

t <- 1:10
pent(t)

##  [1]   1   5  12  22  35  51  70  92 117 145


And see that they are the same as the first ten pentagonal numbers listed in the problemt text.

Next, lets make a nice long list of pentagonal numbers:

t <- 1:10000
t <- pent(t)


Next I'll make all the pair-wise combinations of these numbers:

s <- expand.grid(t,t)


And then I'll filter those combinations:

library(dplyr)

answer<- s %>%
  filter((Var1 + Var2) %in% t) %>%
  filter(abs(Var1 - Var2) %in% t) %>%
  transmute(D = Var1 - Var2) %>%
  abs() %>%
  min()


First - only retain the combinations where the sum of the two pentagonal numbers is itself in the list of pentagonal numbers.

Then, only retain the combinations where the absolute difference is also in the list of pentagonal numbers.

Then calculate a new row D, as the difference.

Pass that to abs() to get the absolute difference.

And finally to min() to get the minimum.

The final two steps are actually unnecessary, since I only find one pair of pentagonal numbers that meets the requirement.

Lessons learned

Hm. Not really. Why is the first I find the solution? Noone else seems to know.